// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFxKahP8j90Zs3W5WPDPkiFU3MjKeXXyk',
    appId: '1:873049750719:web:4e63cc11860edd95cd9a0a',
    messagingSenderId: '873049750719',
    projectId: 'first-bdba0',
    authDomain: 'first-bdba0.firebaseapp.com',
    storageBucket: 'first-bdba0.appspot.com',
    measurementId: 'G-GDQQTDXQQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDubhx_E0AkNAhEuW_2UGPkXC8DPjMqT0s',
    appId: '1:873049750719:android:55d40d9be608b9b9cd9a0a',
    messagingSenderId: '873049750719',
    projectId: 'first-bdba0',
    storageBucket: 'first-bdba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA35kYSpz-4PCjoA-u_GdSDflMhi3kTLdQ',
    appId: '1:873049750719:ios:2093f90d08a152f7cd9a0a',
    messagingSenderId: '873049750719',
    projectId: 'first-bdba0',
    storageBucket: 'first-bdba0.appspot.com',
    iosBundleId: 'com.example.firebaseBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA35kYSpz-4PCjoA-u_GdSDflMhi3kTLdQ',
    appId: '1:873049750719:ios:2093f90d08a152f7cd9a0a',
    messagingSenderId: '873049750719',
    projectId: 'first-bdba0',
    storageBucket: 'first-bdba0.appspot.com',
    iosBundleId: 'com.example.firebaseBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFxKahP8j90Zs3W5WPDPkiFU3MjKeXXyk',
    appId: '1:873049750719:web:8bb3b626098cb78fcd9a0a',
    messagingSenderId: '873049750719',
    projectId: 'first-bdba0',
    authDomain: 'first-bdba0.firebaseapp.com',
    storageBucket: 'first-bdba0.appspot.com',
    measurementId: 'G-XTM96345KN',
  );

}